### ISSUE TITLE
ProtonVPN is not blocked on API but listed in raw.txt

### ISSUE THREAD

**Issue by Timeox2k** [Munzy/blackbox#735]
__Q: What are you currently seeing?__

The site is marking my IP address as  ?

N

__Q: What should it be marked as?__

Y

The site should mark it as ?

Y

Q:  What is the IP Address?

194.126.177.25

__Q: What is the internet provider?__

ProtonVPN

__Q: What other info can you provide us?__
{"result":{"ip":"194.126.177.25","as":"AS209103 Proton AG","city":"Frankfurt am Main","country":"Germany","lat":50.1188,"lon":8.6843,"isp":"Proton AG","org":"Proton Technologies AG","vpn":"N"}}

I noticed that the ASN is listed on https://github.com/Munzy/blackbox/blob/master/blocks/hosting/raw.txt but somehow not detected as a VPN.

**Comment by Munzy** [comment]
Tracked down issue to another system. Testing to see if I can get it resolved.

**Comment by Timeox2k** [comment]
Thank you

**Comment by Munzy** [comment]
I determined the issue to be with our lookup service for ip -> asn. I'll spend a bit more time trying to improve what I can with that service. However, I think this might be down to a few outages I keep seeing pop up with the infrastructure at Digital Ocean. 

As of current the issue is resolved, and the data is being reported correctly.
